// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb7sRIjjLj9rqlvIxbT8yoEDPRNJpec8k',
    appId: '1:657531623440:web:ed7f554a8388203faf1295',
    messagingSenderId: '657531623440',
    projectId: 'homear-intern',
    authDomain: 'homear-intern.firebaseapp.com',
    storageBucket: 'homear-intern.appspot.com',
    measurementId: 'G-2BJ7DCDFBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB2-InEzrgTVU9doXPqWoB0bLR1H9dYVI',
    appId: '1:657531623440:android:53890e6eff06dd77af1295',
    messagingSenderId: '657531623440',
    projectId: 'homear-intern',
    storageBucket: 'homear-intern.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaYFWuy4iGZxkyJehI40gvfdOCyXAJ4Rc',
    appId: '1:657531623440:ios:f7bd28f4cf15c226af1295',
    messagingSenderId: '657531623440',
    projectId: 'homear-intern',
    storageBucket: 'homear-intern.appspot.com',
    androidClientId: '657531623440-77sosbqniuk7ur6plu6itc5v5hc26n58.apps.googleusercontent.com',
    iosClientId: '657531623440-kv6v08orv9hafa499g8snprqepod0k5s.apps.googleusercontent.com',
    iosBundleId: 'com.example.homero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaYFWuy4iGZxkyJehI40gvfdOCyXAJ4Rc',
    appId: '1:657531623440:ios:2c38bbfb59f5b146af1295',
    messagingSenderId: '657531623440',
    projectId: 'homear-intern',
    storageBucket: 'homear-intern.appspot.com',
    androidClientId: '657531623440-77sosbqniuk7ur6plu6itc5v5hc26n58.apps.googleusercontent.com',
    iosClientId: '657531623440-4b14bc5rdoethnacq3l6ifkv13n5baiq.apps.googleusercontent.com',
    iosBundleId: 'com.example.homero.RunnerTests',
  );
}
